version: '3.8'

services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: unless-stopped